

server:
  port: 8765
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery
          lower-case-service-id: true  # Use lowercase service IDs for routing

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

